import { createContext, useEffect, useState } from 'react';

const messages = {
  ES: {
    navbar: {
      flights: 'Vuelos',
      offers: 'Ofertas',
      checkIn: 'Check-in',
      information: 'Información',
      myReservations: 'Mis Reservas',
      admin: '⚙️ Admin',
      login: '👤 Iniciar sesión',
      logout: 'Salir',
      langChangedTitle: 'Idioma cambiado',
      langChangedBody: 'Se ha establecido el idioma a Español para todo el portal.',
      infoTitle: 'Información',
      changeLang: 'Cambiar idioma',
      baggagePolicyTitle: 'Política de Equipaje',
      baggagePolicyBody: 'Todas las tarifas de AeroViajes incluyen un bolso de mano personal de hasta 10kg gratis. El equipaje facturado de hasta 23kg puede añadirse durante la reserva o el check-in.',
      flightStatusTitle: 'Estado de Vuelo',
      flightStatusBody: 'Ingresa el número de vuelo en el buscador principal para ver las horas estimadas de despegue y aterrizaje en tiempo real.',
      supportCenterTitle: 'Centro de Soporte 24/7',
      supportCenterBody: 'Estamos disponibles para ayudarte en cualquier momento del día. Llámanos a la línea nacional gratuita +57 (1) 800-AERO o escríbenos a soporte@aeroviajes.com'
    },
    home: {
      heroTitle: 'El mundo te espera',
      heroSubtitle: 'Reserva vuelos al mejor precio de forma fácil y segura',
      tabRoundtrip: 'Ida y vuelta',
      tabOneWay: 'Solo ida',
      tabMulti: 'Múltiples destinos',
      origin: 'Desde',
      destination: 'Hacia',
      dates: 'Fechas',
      passengersAndClass: 'Pasajeros y clase',
      searchFlights: 'Buscar vuelos',
      bestPriceGuarantee: 'Mejor precio garantizado',
      securePayment: 'Pago seguro',
      attention247: 'Atención 24/7',
      flexibleChanges: 'Cambios flexibles',
      featuredOffers: 'Ofertas destacadas',
      availableFlights: 'Vuelos disponibles',
      loadingFlights: 'Cargando vuelos...',
      noFlights: 'No hay vuelos que coincidan con tu búsqueda.',
      swapTitle: 'Intercambiar origen/destino',
      searchResults: '🔍 Se encontraron {count} vuelo(s) para tu búsqueda.',
      searchShowingAll: 'ℹ️ Mostrando todos los vuelos disponibles para {origen} → {destino}.',
      reservationSuccess: '✅ ¡Reserva realizada con éxito!',
      errorReserveFlight: 'Error al reservar el vuelo.',
      errorLoadFlights: 'No se pudieron cargar los vuelos desde el servidor.',
      standardFare: 'Tarifa Estándar',
      reserving: 'Reservando...',
      reserve: 'Reservar',
      reservationSimulated: 'Reserva simulada enviada.',
      badgeTitleBestPrice: 'Mejor precio garantizado',
      badgeBodyBestPrice: 'Si encuentras la misma ruta más barata, te ayudamos a ajustarla.',
      badgeSubBestPrice: 'Garantía de tarifa más baja',
      badgeTitleSecurePayment: 'Pago seguro',
      badgeBodySecurePayment: 'Tus datos se procesan con encriptación de última generación.',
      badgeSubSecurePayment: 'Protección total de pagos',
      badgeTitleAttention247: 'Atención 24/7',
      badgeBodyAttention247: 'Siempre estamos listos para ayudarte antes, durante y después del viaje.',
      badgeSubAttention247: 'Soporte continuo',
      badgeTitleFlexibleChanges: 'Cambios flexibles',
      badgeBodyFlexibleChanges: 'Modifica tu itinerario con condiciones sencillas y transparentes.',
      badgeSubFlexibleChanges: 'Viaja con tranquilidad',
      rightPanelRegisterHeading: 'Regístrate y recibe ofertas exclusivas',
      rightPanelRegisterDescription: 'Sé el primero en enterarte de promociones y destinos increíbles.',
      rightPanelButtonCreateAccount: 'Crear cuenta',
      rightPanelCheckInTitle: 'Check-in en línea',
      rightPanelCheckInDescription: 'Ahorra tiempo en el aeropuerto.',
      rightPanelCheckInButton: 'Hacer check-in',
      offerPriceFrom: 'Desde USD {price}',
      offerType: {
        roundtrip: 'Ida y vuelta',
        oneway: 'Solo ida',
        multi: 'Múltiples destinos'
      },
      badgeTitleBestPrice: 'Mejor precio garantizado',
      badgeBodyBestPrice: 'Si encuentras la misma ruta más barata, te ayudamos a ajustarla.',
      badgeSubBestPrice: 'Garantía de tarifa más baja',
      badgeTitleSecurePayment: 'Pago seguro',
      badgeBodySecurePayment: 'Tus datos se procesan con encriptación de última generación.',
      badgeSubSecurePayment: 'Protección total de pagos',
      badgeTitleAttention247: 'Atención 24/7',
      badgeBodyAttention247: 'Siempre estamos listos para ayudarte antes, durante y después del viaje.',
      badgeSubAttention247: 'Soporte continuo',
      badgeTitleFlexibleChanges: 'Cambios flexibles',
      badgeBodyFlexibleChanges: 'Modifica tu itinerario con condiciones sencillas y transparentes.',
      badgeSubFlexibleChanges: 'Viaja con tranquilidad',
      featureBaggageTitle: 'Equipaje incluido',
      featureBaggageBody: 'Lleva tu equipaje de mano sin preocupaciones.',
      featureBaggageDesc: 'Consulta la política de equipaje',
      featureMilesTitle: 'Acumula millas',
      featureMilesBody: 'Viaja más y gana beneficios exclusivos.',
      featureMilesDesc: 'Viaja más y obtén beneficios',
      featureSafetyTitle: 'Viajes seguros',
      featureSafetyBody: 'Protocolos de limpieza y salud para tu tranquilidad.',
      featureSafetyDesc: 'Protocolos de bioseguridad',
      featureAppTitle: 'App móvil',
      featureAppBody: 'Gestiona tus viajes desde cualquier lugar.',
      featureAppDesc: 'Gestiona tus viajes desde nuestra app',
      baggageIncluded: 'Equipaje incluido',
      baggageIncludedDesc: 'Consulta la política de equipaje',
      collectMiles: 'Acumula millas',
      collectMilesDesc: 'Viaja más y obtén beneficios',
      safeTravels: 'Viajes seguros',
      safeTravelsDesc: 'Protocolos de bioseguridad',
      mobileApp: 'App móvil',
      mobileAppDesc: 'Gestiona tus viajes desde nuestra app',
      understood: 'Entendido'
    },
    footer: {
      newsletterHeading: '📩 Suscríbete a nuestro boletín',
      newsletterText: 'Recibe ofertas secretas y descuentos de hasta un 40% en tu próximo viaje.',
      newsletterPlaceholder: 'Ingresa tu correo electrónico',
      subscribe: 'Suscribirme',
      subscribedMessage: '¡Gracias! Te avisaremos cuando haya una oferta especial.',
      brandHeading: 'AeroViajes',
      about: 'Tu aerolínea de confianza. Conectamos destinos con la mejor tarifa, seguridad de clase mundial y servicio de excelencia en cada vuelo.',
      aboutBody: 'AeroViajes nace para ofrecer vuelos accesibles con rutas nacionales e internacionales, atención cercana y filosofía de viaje responsable.',
      ourCompany: 'Nuestra Empresa',
      whoWeAre: 'Quiénes somos',
      skyteam: 'Alianza SkyTeam',
      workWithUs: 'Trabaja con nosotros',
      sustainability: 'Sostenibilidad',
      pressRoom: 'Sala de Prensa',
      passengerServices: 'Servicios al Pasajero',
      bookFlights: 'Reserva de vuelos',
      onlineCheckin: 'Check-in en línea',
      flightStatus: 'Estado de vuelos',
      baggagePolicy: 'Política de equipaje',
      seatSelection: 'Selección de asientos',
      helpCenter: 'Centro de ayuda 24/7',
      faqs: 'Preguntas frecuentes',
      specialAssistance: 'Asistencia especial',
      claims: 'Reclamaciones',
      contact: 'Contacto directo',
      contactBody: 'Escríbenos a soporte@aeroviajes.com. Nuestro tiempo de respuesta esperado es menos de 2 horas.',
      skyteamBody: 'Descubre cómo nuestra red SkyTeam amplía las conexiones internacionales con más de 1.000 destinos.',
      workWithUsBody: 'Únete a nuestro equipo y ayuda a construir la experiencia de viaje más humana y cercana en la región.',
      sustainabilityBody: 'Promovemos prácticas verdes en operaciones y compensación de huella de carbono para cada vuelo.',
      pressRoomBody: 'Consulta nuestras últimas noticias, lanzamientos de ruta y novedades corporativas.',
      flightStatusBody: 'Ingresa el número de vuelo en el buscador principal para ver las horas estimadas de despegue y aterrizaje en tiempo real.',
      baggagePolicyBody: 'Todas las tarifas de AeroViajes incluyen un bolso de mano personal de hasta 10kg gratis. El equipaje facturado de hasta 23kg puede añadirse durante la reserva o el check-in.',
      seatSelectionBody: 'Selecciona tu asiento preferido y viaja con mayor comodidad. Disponible en todas las tarifas premium.',
      helpCenterBody: 'Nuestro equipo de atención está listo para resolver tus dudas por chat, llamada o correo electrónico.',
      faqsBody: 'Encuentra respuestas rápidas sobre cambios, equipaje, documentación y servicios a bordo.',
      specialAssistanceBody: 'Solicita atención especial para movilidad reducida, necesidades médicas o acompañantes menores.',
      claimsBody: 'Reporta retrasos, pérdidas o inconvenientes para recibir respuesta y seguimiento formal.',
      privacyPolicy: 'Política de Privacidad',
      privacyPolicyBody: 'Estamos comprometidos con la protección de tus datos personales según la normativa vigente.',
      terms: 'Términos y Condiciones',
      termsBody: 'Todas las compras y reservas están sujetas a los términos y condiciones del transporte aéreo aprobados por la autoridad civil.',
      cookies: 'Política de Cookies',
      cookiesBody: 'Usamos cookies funcionales y analíticas para optimizar tu navegación y ofrecer tarifas personalizadas.',
      rights: 'Derechos del Pasajero',
      rightsBody: 'Conoce la compensación disponible por demoras, cancelaciones o sobreventa bajo regulación aeronáutica.',
      copyright: '© 2026 AeroViajes S.A. Todos los derechos reservados.',
      socialFacebookTitle: 'Facebook',
      socialFacebookBody: 'Síguenos en @AeroViajes para estar al día con promociones y noticias.',
      socialTwitterTitle: 'X (Twitter)',
      socialTwitterBody: 'Síguenos en @AeroViajes para enterarte de ofertas flash en tiempo real.',
      socialInstagramTitle: 'Instagram',
      socialInstagramBody: 'Síguenos en @AeroViajes para ver fotos de nuestros destinos favoritos y detrás de escenas.',
      socialLinkedInTitle: 'LinkedIn',
      socialLinkedInBody: 'Conéctate con nuestra página corporativa para ver oportunidades profesionales.',
      socialYouTubeTitle: 'YouTube',
      socialYouTubeBody: 'Suscríbete a nuestro canal para guías de viaje y tours de cabina.'
    },
    auth: {
      loginTitle: 'Iniciar sesión',
      loginSubtitle: 'Ingresa a tu cuenta de AeroViajes',
      emailLabel: 'Correo electrónico',
      emailPlaceholder: 'ejemplo@aeroviajes.com',
      passwordLabel: 'Contraseña',
      passwordPlaceholder: '••••••••',
      loginButton: 'Iniciar sesión',
      loggingIn: 'Ingresando...',
      noAccount: '¿No tienes cuenta?',
      registerLink: 'Regístrate gratis',
      registerTitle: 'Crear cuenta ✨',
      registerSubtitle: 'Regístrate para reservar tus vuelos',
      nameLabel: 'Nombre completo',
      namePlaceholder: 'Juan Pérez',
      emailLabelRegister: 'Email',
      passwordLabelRegister: 'Contraseña',
      passwordPlaceholderRegister: 'Mínimo 6 caracteres',
      registerButton: 'Registrarse',
      alreadyHaveAccount: '¿Ya tienes cuenta?',
      loginNow: 'Iniciar sesión',
      errorConnection: 'Error de conexión',
      passwordTooShort: 'La contraseña debe tener al menos 6 caracteres',
      creatingAccount: 'Creando cuenta...'
    },
    checkIn: {
      title: 'Check-in en Línea',
      subtitle: 'Obtén tu pase de abordar de forma inmediata',
      pnrLabel: 'Código de reserva (PNR)',
      pnrPlaceholder: 'Ej: AV-8492',
      lastNameLabel: 'Primer apellido del pasajero',
      lastNamePlaceholder: 'Ej: Perez',
      getBoardingPass: 'Obtener Pase de Abordar',
      successTitle: '¡Check-in Exitoso!',
      successSubtitle: 'Tu pase de abordar está listo',
      downloadButton: 'Descargar Pase / Finalizar',
      errorCompleteFields: 'Por favor completa todos los campos.',
      passengerLabel: 'Pasajero',
      flightLabel: 'Vuelo',
      seatLabel: 'Asiento',
      gateLabel: 'Puerta',
      boardingLabel: 'Embarque',
      routeLabel: 'Ruta',
      statusConfirmed: 'CONFIRMADO 🟢'
    },
    reservas: {
      title: '🎫 Mis Reservas',
      subtitle: 'Gestiona tus vuelos reservados y obtén tus pases de abordar',
      reserveNew: '+ Reservar nuevo vuelo',
      noReservations: 'No tienes reservas activas',
      noReservationsDescription: 'Encuentra las mejores ofertas de vuelos y comienza a planear tu próximo destino.',
      exploreFlights: 'Explorar Vuelos',
      reservationCode: 'Código de reserva',
      passenger: 'Pasajero',
      boarding: 'Embarque',
      seat: 'Asiento',
      gate: 'Puerta',
      totalFare: 'Total',
      passengerFallback: 'Pasajero',
      confirmed: 'Confirmado 🟢',
      boardingPass: '🎫 Pase de abordar',
      cancelTrip: 'Cancelar viaje',
      canceling: 'Cancelando...',
      confirmCancel: '¿Estás seguro de cancelar esta reserva?',
      errorCancel: 'Error al intentar cancelar la reserva.',
      errorLoad: 'No se pudieron cargar tus reservas. Por favor intenta de nuevo.'
    },
    admin: {
      title: '⚙️ Panel de Administración',
      subtitle: 'Gestiona vuelos y reservas',
      newFlight: '➕ Nuevo vuelo',
      originCity: 'Ciudad origen',
      destinationCity: 'Ciudad destino',
      priceUsd: 'Precio (USD)',
      createFlight: 'Crear vuelo',
      creating: 'Creando...',
      flightsTab: '✈️ Vuelos',
      reservationsTab: '🎫 Reservas',
      noFlights: 'Sin vuelos',
      noFlightsDescription: 'Crea el primer vuelo usando el formulario.',
      noReservations: 'Sin reservas',
      noReservationsDescription: 'Aún no hay reservas registradas.',
      delete: 'Eliminar',
      createSuccess: '✅ Vuelo creado exitosamente',
      errorCreating: 'Error creando vuelo',
      deleteConfirm: '¿Estás seguro de eliminar este vuelo y todas sus reservas?',
      deleteSuccess: '✅ Vuelo eliminado',
      errorDeleting: 'Error eliminando vuelo',
      errorLoadingData: 'Error cargando datos',
      colId: 'ID',
      colOrigin: 'Origen',
      colDestination: 'Destino',
      colPrice: 'Precio',
      colAction: 'Acción',
      colUser: 'Usuario',
      colEmail: 'Email',
      colRoute: 'Ruta'
    },
    infoModal: {
      okButton: 'Entendido'
    }
  },
  EN: {
    navbar: {
      flights: 'Flights',
      offers: 'Offers',
      checkIn: 'Check-in',
      information: 'Information',
      admin: '⚙️ Admin',
      login: '👤 Log in',
      logout: 'Log out',
      langChangedTitle: 'Language Changed',
      langChangedBody: 'English has been set for the entire portal.',
      infoTitle: 'Information',
      changeLang: 'Change language',
      baggagePolicyTitle: 'Baggage policy',
      baggagePolicyBody: 'All fares include one personal cabin bag up to 10kg. Checked baggage up to 23kg can be added during booking or check-in.',
      flightStatusTitle: 'Flight Status',
      flightStatusBody: 'Enter the flight number in the main search to see estimated departure and arrival times in real time.',
      supportCenterTitle: 'Support Center 24/7',
      supportCenterBody: 'We are available to help you at any time of day. Call our free line or email support@aeroviajes.com'
    },
    home: {
      heroTitle: 'The world is waiting for you',
      heroSubtitle: 'Book flights at the best price easily and securely',
      tabRoundtrip: 'Round-trip',
      tabOneWay: 'One-way',
      tabMulti: 'Multi-city',
      origin: 'From',
      destination: 'To',
      dates: 'Dates',
      passengersAndClass: 'Passengers & class',
      searchFlights: 'Search flights',
      bestPriceGuarantee: 'Best price guaranteed',
      securePayment: 'Secure payment',
      attention247: '24/7 support',
      flexibleChanges: 'Flexible changes',
      featuredOffers: 'Featured offers',
      availableFlights: 'Available flights',
      loadingFlights: 'Loading flights...',
      noFlights: 'No flights match your search.',
      swapTitle: 'Swap origin/destination',
      searchResults: '🔍 Found {count} flight(s) for your search.',
      searchShowingAll: 'ℹ️ Showing all available flights for {origen} → {destino}.',
      reservationSuccess: '✅ Booking completed successfully!',
      errorReserveFlight: 'Error booking the flight.',
      errorLoadFlights: 'Could not load flights from the server.',
      standardFare: 'Standard Fare',
      reserve: 'Book now',
      reservationSimulated: 'Simulated booking sent.',
      rightPanelRegisterHeading: 'Sign up and get exclusive offers',
      rightPanelRegisterDescription: 'Be the first to find out about promotions and amazing destinations.',
      rightPanelButtonCreateAccount: 'Create account',
      rightPanelCheckInTitle: 'Online check-in',
      rightPanelCheckInDescription: 'Save time at the airport.',
      rightPanelCheckInButton: 'Do check-in',
      offerPriceFrom: 'From USD {price}',
      offerType: {
        roundtrip: 'Round-trip',
        oneway: 'One-way',
        multi: 'Multi-city'
      },
      reserving: 'Reserving...',
      reservationSimulated: 'Simulated booking sent.',
      defaultDateRange: 'Jun 15 – Jun 22',
      defaultPassengersClass: '1 passenger, Economy',
      badgeTitleBestPrice: 'Best price guaranteed',
      badgeBodyBestPrice: 'If you find the same route cheaper, we help adjust it.',
      badgeSubBestPrice: 'Lowest fare guarantee',
      badgeTitleSecurePayment: 'Secure payment',
      badgeBodySecurePayment: 'Your information is processed with end-to-end encryption.',
      badgeSubSecurePayment: 'Full payment protection',
      badgeTitleAttention247: '24/7 support',
      badgeBodyAttention247: 'We are ready to help before, during and after your trip.',
      badgeSubAttention247: 'Continuous support',
      badgeTitleFlexibleChanges: 'Flexible changes',
      badgeBodyFlexibleChanges: 'Change your itinerary with simple and transparent conditions.',
      badgeSubFlexibleChanges: 'Travel with peace of mind',
      featureBaggageTitle: 'Baggage included',
      featureBaggageBody: 'Carry your cabin baggage without worries.',
      featureBaggageDesc: 'Check baggage policy',
      featureMilesTitle: 'Collect miles',
      featureMilesBody: 'Travel more and unlock exclusive rewards.',
      featureMilesDesc: 'Travel more and earn rewards',
      featureSafetyTitle: 'Safe travels',
      featureSafetyBody: 'Cleaning and safety protocols for your peace of mind.',
      featureSafetyDesc: 'Health and hygiene protocols',
      featureAppTitle: 'Mobile app',
      featureAppBody: 'Manage your trips from anywhere.',
      featureAppDesc: 'Manage your trips from our app',
      baggageIncluded: 'Baggage included',
      baggageIncludedDesc: 'Check baggage policy',
      collectMiles: 'Collect miles',
      collectMilesDesc: 'Travel more and earn rewards',
      safeTravels: 'Safe travels',
      safeTravelsDesc: 'Health and hygiene protocols',
      mobileApp: 'Mobile app',
      mobileAppDesc: 'Manage your trips from our app',
      understood: 'Understood'
    },
    footer: {
      newsletterHeading: '📩 Subscribe to our newsletter',
      newsletterText: 'Receive secret offers and discounts of up to 40% on your next trip.',
      newsletterPlaceholder: 'Enter your email address',
      subscribe: 'Subscribe',
      subscribedMessage: 'Thanks! We will notify you when there is a special offer.',
      brandHeading: 'AeroViajes',
      about: 'Your trusted airline. We connect destinations with the best fare, world-class safety and excellent service on every flight.',
      aboutBody: 'AeroViajes was created to offer affordable flights with national and international routes, warm service and a responsible travel mindset.',
      ourCompany: 'Our Company',
      whoWeAre: 'Who we are',
      skyteam: 'SkyTeam Alliance',
      workWithUs: 'Work with us',
      sustainability: 'Sustainability',
      pressRoom: 'Press Room',
      passengerServices: 'Passenger Services',
      bookFlights: 'Flight booking',
      onlineCheckin: 'Online check-in',
      flightStatus: 'Flight status',
      baggagePolicy: 'Baggage policy',
      seatSelection: 'Seat selection',
      helpCenter: 'Help center 24/7',
      faqs: 'FAQs',
      specialAssistance: 'Special assistance',
      claims: 'Claims',
      contact: 'Direct contact',
      contactBody: 'Write to us at support@aeroviajes.com. Our expected response time is under 2 hours.',
      skyteamBody: 'Discover how our SkyTeam network expands international connections to over 1,000 destinations.',
      workWithUsBody: 'Join our team and help build the most human and customer-first travel experience in the region.',
      sustainabilityBody: 'We promote green operations and carbon offset practices for every flight.',
      pressRoomBody: 'Check our latest news, route launches, and corporate updates.',
      flightStatusBody: 'Enter the flight number in the main search to see estimated departure and arrival times in real time.',
      baggagePolicyBody: 'All fares include one personal cabin bag up to 10kg. Checked baggage up to 23kg can be added during booking or check-in.',
      seatSelectionBody: 'Choose your preferred seat and travel with more comfort. Available on Premium fares.',
      helpCenterBody: 'Our support team is ready to answer your questions by chat, phone, or email.',
      faqsBody: 'Find quick answers about changes, baggage, documentation, and onboard services.',
      specialAssistanceBody: 'Request special assistance for reduced mobility, medical needs, or unaccompanied minors.',
      claimsBody: 'Report delays, losses, or issues to receive formal follow-up and support.',
      privacyPolicy: 'Privacy Policy',
      privacyPolicyBody: 'We are committed to protecting your personal data in accordance with applicable data protection law.',
      terms: 'Terms and Conditions',
      termsBody: 'All purchases and bookings are subject to the Carrier Transportation Terms and Conditions approved by the civil aviation authority.',
      cookies: 'Cookies Policy',
      cookiesBody: 'We use functional and analytics cookies to optimize your browsing experience and deliver personalized fares.',
      rights: 'Passenger rights',
      rightsBody: 'Learn about compensation available for delays, cancellations or overbooking under aviation regulations.',
      copyright: '© 2026 AeroViajes S.A. All rights reserved.',
      socialFacebookTitle: 'Facebook',
      socialFacebookBody: 'Follow us on @AeroViajes to stay up to date with promotions and news.',
      socialTwitterTitle: 'X (Twitter)',
      socialTwitterBody: 'Follow us on @AeroViajes for flash deals in real time.',
      socialInstagramTitle: 'Instagram',
      socialInstagramBody: 'Follow us on @AeroViajes to see photos of our favorite destinations and behind the scenes.',
      socialLinkedInTitle: 'LinkedIn',
      socialLinkedInBody: 'Connect with our corporate page to see professional opportunities.',
      socialYouTubeTitle: 'YouTube',
      socialYouTubeBody: 'Subscribe to our channel for travel guides and cabin tours.',
      privacyPolicy: 'Privacy Policy',
      privacyPolicyBody: 'We are committed to protecting your personal data in accordance with applicable data protection law.',
      terms: 'Terms and Conditions',
      termsBody: 'All purchases and bookings are subject to the Carrier Transportation Terms and Conditions approved by the civil aviation authority.',
      cookies: 'Cookies Policy',
      cookiesBody: 'We use functional and analytics cookies to optimize your browsing experience and deliver personalized fares.',
      rights: 'Passenger rights',
      rightsBody: 'Learn about compensation available for delays, cancellations or overbooking under aviation regulations.',
      copyright: '© 2026 AeroViajes S.A. All rights reserved.'
    },
    auth: {
      loginTitle: 'Log in',
      loginSubtitle: 'Sign in to your AeroViajes account',
      emailLabel: 'Email address',
      emailPlaceholder: 'example@aeroviajes.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      loginButton: 'Log in',
      loggingIn: 'Signing in...',
      noAccount: 'Don’t have an account?',
      registerLink: 'Register for free',
      registerTitle: 'Create account ✨',
      registerSubtitle: 'Register to book your flights',
      nameLabel: 'Full name',
      namePlaceholder: 'John Doe',
      emailLabelRegister: 'Email',
      passwordLabelRegister: 'Password',
      passwordPlaceholderRegister: 'At least 6 characters',
      registerButton: 'Register',
      alreadyHaveAccount: 'Already have an account?',
      loginNow: 'Log in',
      errorConnection: 'Connection error',
      passwordTooShort: 'Password must be at least 6 characters',
      creatingAccount: 'Creating account...'
    },
    checkIn: {
      title: 'Online Check-in',
      subtitle: 'Get your boarding pass instantly',
      pnrLabel: 'Reservation code (PNR)',
      pnrPlaceholder: 'Eg: AV-8492',
      lastNameLabel: 'Passenger last name',
      lastNamePlaceholder: 'Eg: Perez',
      getBoardingPass: 'Get boarding pass',
      successTitle: 'Check-in Successful!',
      successSubtitle: 'Your boarding pass is ready',
      downloadButton: 'Download Pass / Finish',
      errorCompleteFields: 'Please complete all fields.',
      passengerLabel: 'Passenger',
      flightLabel: 'Flight',
      seatLabel: 'Seat',
      gateLabel: 'Gate',
      boardingLabel: 'Boarding',
      routeLabel: 'Route',
      statusConfirmed: 'CONFIRMED 🟢'
    },
    reservas: {
      title: '🎫 My Bookings',
      subtitle: 'Manage your booked flights and get your boarding passes',
      reserveNew: '+ Book new flight',
      noReservations: 'You have no active bookings',
      noReservationsDescription: 'Find the best flight deals and start planning your next destination.',
      exploreFlights: 'Explore Flights',
      reservationCode: 'Reservation code',
      passenger: 'Passenger',
      boarding: 'Boarding',
      seat: 'Seat',
      gate: 'Gate',
      totalFare: 'Total',
      passengerFallback: 'Passenger',
      confirmed: 'Confirmed 🟢',
      boardingPass: '🎫 Boarding pass',
      cancelTrip: 'Cancel trip',
      canceling: 'Canceling...',
      confirmCancel: 'Are you sure you want to cancel this booking?',
      errorCancel: 'Error trying to cancel the booking.',
      errorLoad: 'Could not load your bookings. Please try again.'
    },
    admin: {
      title: '⚙️ Admin Panel',
      subtitle: 'Manage flights and bookings',
      newFlight: '➕ New flight',
      originCity: 'Origin city',
      destinationCity: 'Destination city',
      priceUsd: 'Price (USD)',
      createFlight: 'Create flight',
      creating: 'Creating...',
      createSuccess: '✅ Flight created successfully',
      errorCreating: 'Error creating flight',
      deleteConfirm: 'Are you sure you want to delete this flight and all its bookings?',
      deleteSuccess: '✅ Flight deleted',
      errorDeleting: 'Error deleting flight',
      errorLoadingData: 'Error loading data',
      flightsTab: '✈️ Flights',
      reservationsTab: '🎫 Bookings',
      noFlights: 'No flights',
      noFlightsDescription: 'Create the first flight using the form.',
      noReservations: 'No bookings',
      noReservationsDescription: 'There are no bookings registered yet.',
      delete: 'Delete'
    },
    infoModal: {
      okButton: 'Understood'
    }
  }
};

export const LanguageContext = createContext({
  lang: 'ES',
  toggleLang: () => {},
  setLang: () => {},
  t: () => ''
});

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('ES');

  useEffect(() => {
    const storedLang = localStorage.getItem('lang');
    if (storedLang === 'ES' || storedLang === 'EN') {
      setLang(storedLang);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const toggleLang = () => {
    setLang((prev) => (prev === 'ES' ? 'EN' : 'ES'));
  };

  const t = (key, paramsOrOverrideLang = {}, overrideLang = lang) => {
    let params = {};
    if (typeof paramsOrOverrideLang === 'string') {
      overrideLang = paramsOrOverrideLang;
    } else if (typeof paramsOrOverrideLang === 'object' && paramsOrOverrideLang !== null) {
      params = paramsOrOverrideLang;
    }

    const value = key.split('.').reduce((obj, part) => (obj && obj[part] !== undefined ? obj[part] : undefined), messages[overrideLang]);
    if (value === undefined) return key;
    if (typeof value !== 'string') return value;

    return value.replace(/\{(\w+)\}/g, (_, name) =>
      params[name] !== undefined ? params[name] : `{${name}}`
    );
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
